package replica_friendly_end;


/**
* replica_friendly_end/FlightReservationServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/SOEN423_Project/Jeremy_Replica/src/FlightReservationServer.idl
* Wednesday, November 16, 2016 12:54:47 AM EST
*/

public interface FlightReservationServer extends FlightReservationServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationServer
