package replica_friendly_end;

/**
* replica_friendly_end/FlightReservationServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/SOEN423_Project/Jeremy_Replica/src/FlightReservationServer.idl
* Wednesday, November 16, 2016 12:54:47 AM EST
*/

public final class FlightReservationServerHolder implements org.omg.CORBA.portable.Streamable
{
  public replica_friendly_end.FlightReservationServer value = null;

  public FlightReservationServerHolder ()
  {
  }

  public FlightReservationServerHolder (replica_friendly_end.FlightReservationServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = replica_friendly_end.FlightReservationServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    replica_friendly_end.FlightReservationServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return replica_friendly_end.FlightReservationServerHelper.type ();
  }

}
