package FlightBookingServer;


/**
* FlightBookingServer/FlightServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBookingServer.idl
* Thursday, November 17, 2016 12:13:00 o'clock AM EST
*/

public interface FlightServerInterface extends FlightServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightServerInterface
