package FlightBookingServer;


/**
* FlightBookingServer/FlightServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBookingServer.idl
* Thursday, November 17, 2016 12:13:00 o'clock AM EST
*/

abstract public class FlightServerInterfaceHelper
{
  private static String  _id = "IDL:FlightBookingServer/FlightServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FlightBookingServer.FlightServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FlightBookingServer.FlightServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FlightBookingServer.FlightServerInterfaceHelper.id (), "FlightServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FlightBookingServer.FlightServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlightServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FlightBookingServer.FlightServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FlightBookingServer.FlightServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FlightBookingServer.FlightServerInterface)
      return (FlightBookingServer.FlightServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FlightBookingServer._FlightServerInterfaceStub stub = new FlightBookingServer._FlightServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FlightBookingServer.FlightServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FlightBookingServer.FlightServerInterface)
      return (FlightBookingServer.FlightServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FlightBookingServer._FlightServerInterfaceStub stub = new FlightBookingServer._FlightServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
