package friendly_end;


/**
* fe/FlightReservationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/SOEN423_Project/CORBA_DFRS/src/FlightReservationServer.idl
* Tuesday, November 15, 2016 10:00:42 PM EST
*/

public interface FlightReservationServerOperations 
{
  String bookFlight (String firstName, String lastName, String address, String phoneNumber, String destination, String date, String flightClass);
  String getBookedFlightCount (String recordType);
  String editFlightRecord (String recordId, String fieldName, String newValue);
  String transferReservation (String passengerId, String currentCity, String otherCity);
  String[] getFlights ();
  String[] getReservations ();
} // interface FlightReservationServerOperations
