package friendly_end;

/**
* fe/FlightReservationServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/SOEN423_Project/CORBA_DFRS/src/FlightReservationServer.idl
* Tuesday, November 15, 2016 10:00:42 PM EST
*/

public final class FlightReservationServerHolder implements org.omg.CORBA.portable.Streamable
{
  public friendly_end.FlightReservationServer value = null;

  public FlightReservationServerHolder ()
  {
  }

  public FlightReservationServerHolder (friendly_end.FlightReservationServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = friendly_end.FlightReservationServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    friendly_end.FlightReservationServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return friendly_end.FlightReservationServerHelper.type ();
  }

}
