package friendly_end;


/**
* fe/FlightReservationServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/SOEN423_Project/CORBA_DFRS/src/FlightReservationServer.idl
* Tuesday, November 15, 2016 10:00:42 PM EST
*/

public interface FlightReservationServer extends FlightReservationServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationServer
