package friendly_end;


/**
* fe/FlightReservationServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jerem/Source/Repos/SOEN423_Project/CORBA_DFRS/src/FlightReservationServer.idl
* Tuesday, November 15, 2016 10:00:42 PM EST
*/

public abstract class FlightReservationServerPOA extends org.omg.PortableServer.Servant
 implements friendly_end.FlightReservationServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
    _methods.put ("getFlights", new java.lang.Integer (4));
    _methods.put ("getReservations", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // fe/FlightReservationServer/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phoneNumber = in.read_string ();
         String destination = in.read_string ();
         String date = in.read_string ();
         String flightClass = in.read_string ();
         String $result = null;
         $result = this.bookFlight (firstName, lastName, address, phoneNumber, destination, date, flightClass);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // fe/FlightReservationServer/getBookedFlightCount
       {
         String recordType = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // fe/FlightReservationServer/editFlightRecord
       {
         String recordId = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editFlightRecord (recordId, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // fe/FlightReservationServer/transferReservation
       {
         String passengerId = in.read_string ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (passengerId, currentCity, otherCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // fe/FlightReservationServer/getFlights
       {
         String $result[] = null;
         $result = this.getFlights ();
         out = $rh.createReply();
         friendly_end.stringsHelper.write (out, $result);
         break;
       }

       case 5:  // fe/FlightReservationServer/getReservations
       {
         String $result[] = null;
         $result = this.getReservations ();
         out = $rh.createReply();
         friendly_end.stringsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:fe/FlightReservationServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightReservationServer _this() 
  {
    return FlightReservationServerHelper.narrow(
    super._this_object());
  }

  public FlightReservationServer _this(org.omg.CORBA.ORB orb) 
  {
    return FlightReservationServerHelper.narrow(
    super._this_object(orb));
  }


} // class FlightReservationServerPOA
