package jeremy_replica.friendly_end;


/**
* friendly_end/FlightReservationServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jeremy/Source/Repos/SOEN423_Project/Jeremy_Replica/src/FlightReservationServer.idl
* Sunday, December 4, 2016 6:10:02 PM EST
*/

public interface FlightReservationServerOperations 
{
  String bookFlight (String firstName, String lastName, String address, String phoneNumber, String destination, String date, String flightClass);
  String getBookedFlightCount (String bookedFlightCountRequest);
  String editFlightRecord (String editFlightRecordRequest, String fieldToEdit, String newValue);
  String transferReservation (String transferReservationRequest, String currentCity, String otherCity);
  String[] getFlightRecords ();
  String[] getFlightReservations ();
  String[] getPassengerRecords ();
  String[] getManagerRecords ();
} // interface FlightReservationServerOperations
