package jeremy_replica.friendly_end;


/**
* friendly_end/FlightReservationServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Jeremy/Source/Repos/SOEN423_Project/Jeremy_Replica/src/FlightReservationServer.idl
* Sunday, December 4, 2016 6:10:02 PM EST
*/

public interface FlightReservationServer extends FlightReservationServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightReservationServer
