package flight_reservation_system;


/**
* FlightReservationApp/FlightReservationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightReservationApp.idl
* Wednesday, November 30, 2016 11:30:31 o'clock PM EST
*/

public interface FlightReservationOperations 
{
  String bookFlight (String firstName, String lastName, String address, String phone, String destination, String date, String seating);
  String getBookedFlightCount (String recordType);
  String editFlightRecord (int recordID, String fieldName, String newValue);
  String transferReservation (int passengerID, String currentCity, String otherCity);
  String displayRecords ();
  String displayPassengerRecords ();
  String getServerName ();
  String getCityCode ();
  String getPortNumber ();
} // interface FlightReservationOperations
