package flight_reservation_system;


/**
* FlightReservationApp/FlightReservationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightReservationApp.idl
* Wednesday, November 30, 2016 11:30:31 o'clock PM EST
*/

public abstract class FlightReservationPOA extends org.omg.PortableServer.Servant
 implements flight_reservation_system.FlightReservationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookFlight", new java.lang.Integer (0));
    _methods.put ("getBookedFlightCount", new java.lang.Integer (1));
    _methods.put ("editFlightRecord", new java.lang.Integer (2));
    _methods.put ("transferReservation", new java.lang.Integer (3));
    _methods.put ("displayRecords", new java.lang.Integer (4));
    _methods.put ("displayPassengerRecords", new java.lang.Integer (5));
    _methods.put ("getServerName", new java.lang.Integer (6));
    _methods.put ("getCityCode", new java.lang.Integer (7));
    _methods.put ("getPortNumber", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FlightReservationApp/FlightReservation/bookFlight
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String destination = in.read_string ();
         String date = in.read_string ();
         String seating = in.read_string ();
         String $result = null;
         $result = this.bookFlight (firstName, lastName, address, phone, destination, date, seating);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FlightReservationApp/FlightReservation/getBookedFlightCount
       {
         String recordType = in.read_string ();
         String $result = null;
         $result = this.getBookedFlightCount (recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FlightReservationApp/FlightReservation/editFlightRecord
       {
         int recordID = in.read_long ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editFlightRecord (recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // FlightReservationApp/FlightReservation/transferReservation
       {
         int passengerID = in.read_long ();
         String currentCity = in.read_string ();
         String otherCity = in.read_string ();
         String $result = null;
         $result = this.transferReservation (passengerID, currentCity, otherCity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FlightReservationApp/FlightReservation/displayRecords
       {
         String $result = null;
         $result = this.displayRecords ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // FlightReservationApp/FlightReservation/displayPassengerRecords
       {
         String $result = null;
         $result = this.displayPassengerRecords ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FlightReservationApp/FlightReservation/getServerName
       {
         String $result = null;
         $result = this.getServerName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // FlightReservationApp/FlightReservation/getCityCode
       {
         String $result = null;
         $result = this.getCityCode ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // FlightReservationApp/FlightReservation/getPortNumber
       {
         String $result = null;
         $result = this.getPortNumber ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FlightReservationApp/FlightReservation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightReservation _this() 
  {
    return FlightReservationHelper.narrow(
    super._this_object());
  }

  public FlightReservation _this(org.omg.CORBA.ORB orb) 
  {
    return FlightReservationHelper.narrow(
    super._this_object(orb));
  }


} // class FlightReservationPOA
