package caio_replica.FlightBookingServer;


/**
* FlightBookingServer/FlightServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBookingServer.idl
* Thursday, November 17, 2016 12:13:00 o'clock AM EST
*/

public interface FlightServerInterfaceOperations 
{
  String bookFlight (String firstName, String lastName, String address, String tel, String dest, String date, String flightClass);
  String getBookedFlightCount (String recordType);
  String editFlightRecord (String recordID, String fieldName, String newValue);
  String transferReservation (String PassengerID, String currentCity, String otherCity);
} // interface FlightServerInterfaceOperations
