package caio_replica.FlightBookingServer;

/**
* FlightBookingServer/FlightServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBookingServer.idl
* Thursday, November 17, 2016 12:13:00 o'clock AM EST
*/

public final class FlightServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public caio_replica.FlightBookingServer.FlightServerInterface value = null;

  public FlightServerInterfaceHolder ()
  {
  }

  public FlightServerInterfaceHolder (caio_replica.FlightBookingServer.FlightServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = caio_replica.FlightBookingServer.FlightServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    caio_replica.FlightBookingServer.FlightServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return caio_replica.FlightBookingServer.FlightServerInterfaceHelper.type ();
  }

}
